### PR TITLE
Bump mender-artifact to version 3.6.1

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
@oleorhagen How do you plan to do this? If you use the tag, you will not be able to build it until we finish the release (and hence publish `mender-artifact 3.7.0`) :thinking: I think latest released version is enough for `create-artifact-worker` requirements.

**Comment by oleorhagen** [comment]
> @oleorhagen How do you plan to do this? If you use the tag, you will not be able to build it until we finish the release (and hence publish `mender-artifact 3.7.0`) thinking I think latest released version is enough for `create-artifact-worker` requirements.

I was not sure how to do this magic in the meantime, but if the old release is good enough, then this certainly makes it a lot easier, although, it's also a little odd, including it in the release, sort of alongside `3.7` for the mainline

**Comment by lluiscampos** [comment]
Discussed over Slack - I vote for keeping it simple and just using the previously released version of the tool.

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Pull request merged**
