### PR TITLE
Rebuild to upgrade to the latest back-incompatible workflows client

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
The backend integration tests passed (both OS & ENT). Ignore all the other failures, due to the transition to the workflows service which uses nats as message broker.

**Review by kacf — APPROVED** [review]
My approval is mostly approval of intention. I know little about how this service works.

Is there a task for fixing the "workflows:master" problem? I guess [MEN-4843](https://tracker.mender.io/browse/MEN-4843) is more about fixing it for the users of this service, not the service itself.

**Comment by tranchitella** [comment]
@kacf I think this PR tries to address the issue:
https://github.com/mendersoftware/create-artifact-worker/pull/72

**Review by alfrunes — APPROVED** [review]

**Pull request merged**
