### PR TITLE
MEN-4179: bugfix to allow spaces in artifact names

### PR DESCRIPTION
**Pull request by tranchitella**
This is an empty commit, it triggers a rebuild to download the latest
single-file-artifact-gen.

Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
Zero changes..? Is it just to document the changelog, or is something missing?

**Comment by kacf** [comment]
Ah, doh! I need to read the commit message properly. But why does this work? Does it always download the latest one? That does not sound compatible with on-prem releases.

**Comment by tranchitella** [comment]
@kacf it downloads the file from master:
https://github.com/mendersoftware/create-artifact-worker/blob/master/Dockerfile#L32

I fixed it here:
https://github.com/mendersoftware/mender/pull/704

Wrong approach?

**Review by alfrunes — APPROVED** [review]

**Comment by tranchitella** [comment]
@kacf @lluiscampos green light on this one? We would like to deploy it to HM.

**Comment by kacf** [comment]
The whitespace fix is correct, of course.

Downloading from master I think is not correct. It means you will always get it from master, and the container will be different every time you build it. In fact, this very commit is kind of useless, it is not possible to revert it, for instance.

However, the problem is preexisting, so it's not really something I want to push through in this commit. I talked to @lluiscampos about it, and we don't really have a good solution for it off the top of our heads. So this is good to go, I think.

**Pull request merged**
