### PR TITLE
MEN-4409: upgrade mender-artifact to version 3.5.0

### PR DESCRIPTION
**Pull request by tranchitella**
This enables the create-artifact-worker to generate artifacts that
implement the provides and clear provides fields.

Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
This fixes the current issue but does not prevent a similar bug to happen in the future.

A better solution is to use `release_tool` to install the exact mender artifact corresponding to the version being built of create-artifact-worker - this would result in master here, but would have resulted in 3.5.0 on the release build.

**Comment by tranchitella** [comment]
@lluiscampos this is an interesting approach, do you want me to rework the PR? Is it acceptable to clone integration in the Dockerfile, to extract this information? It will probably require a multi-stage build, though. Do we have examples in our codebase?

**Comment by kacf** [comment]
It's possible, but also a bit tricky. If the build is running in a pull request, the branch name will be `pr_xxx` which won't match anything. So you will need to get the target branch through Gitlab variables. Which then won't work if you run it locally.

I like the incentive, but it sounds a bit error prone... What do you think, @lluiscampos?

**Comment by tranchitella** [comment]
@lluiscampos ping?

**Comment by lluiscampos** [comment]
@tranchitella @kacf I approved because I knew this was a bit far fetched.

It is quite tricky this one, because we cannot just update it during the release process.

An alternative I can think of, is to use the same approach that we did for mender-convert/mender -> to publish somewhere the "latest" mender-artifact and install that instead. Does this sound better to you? I can create the JIRA task for it.

In any case, this PR is good to go.

**Comment by kacf** [comment]
> An alternative I can think of, is to use the same approach that we did for mender-convert/mender -> to publish somewhere the "latest" mender-artifact and install that instead. Does this sound better to you? I can create the JIRA task for it.

I think this will not work for on-prem releases, will it? Indeed tricky...

I would consider putting it in the release checklist for the time being at least, so it's not forgotten. We can think about optimizing it later.

**Pull request merged**
